# -*- coding: utf-8 -*-
"""my_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUmjTr3P3TY8-MHQ1X-Mu9DRThEnqE9s
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('csv.trees.csv')

features = {"address", "species", "age", "health", "height"}

df.sample(2)

df.dtypes

df['TEMON'].hist(bins=20, figsize=(10, 8))
plt.savefig("histograms.TEMON.png")
plt.close()